// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: restaurant.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type Restaurant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,8,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	OpeningTime   string                 `protobuf:"bytes,9,opt,name=opening_time,json=openingTime,proto3" json:"opening_time,omitempty"`
	ClosingTime   string                 `protobuf:"bytes,10,opt,name=closing_time,json=closingTime,proto3" json:"closing_time,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	mi := &file_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *Restaurant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Restaurant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Restaurant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Restaurant) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Restaurant) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Restaurant) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Restaurant) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Restaurant) GetOpeningTime() string {
	if x != nil {
		return x.OpeningTime
	}
	return ""
}

func (x *Restaurant) GetClosingTime() string {
	if x != nil {
		return x.ClosingTime
	}
	return ""
}

func (x *Restaurant) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Restaurant) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId  string                 `protobuf:"bytes,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,7,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	Category      string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItem) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MenuItem) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *MenuItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MenuItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MenuItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetRestaurantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantsRequest) Reset() {
	*x = GetRestaurantsRequest{}
	mi := &file_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantsRequest) ProtoMessage() {}

func (x *GetRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *GetRestaurantsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetRestaurantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*Restaurant          `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantsResponse) Reset() {
	*x = GetRestaurantsResponse{}
	mi := &file_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantsResponse) ProtoMessage() {}

func (x *GetRestaurantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantsResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantsResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *GetRestaurantsResponse) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *GetRestaurantsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantRequest) Reset() {
	*x = GetRestaurantRequest{}
	mi := &file_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantRequest) ProtoMessage() {}

func (x *GetRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *GetRestaurantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurant    *Restaurant            `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantResponse) Reset() {
	*x = GetRestaurantResponse{}
	mi := &file_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantResponse) ProtoMessage() {}

func (x *GetRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *GetRestaurantResponse) GetRestaurant() *Restaurant {
	if x != nil {
		return x.Restaurant
	}
	return nil
}

type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *GetMenuRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *GetMenuRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuResponse) Reset() {
	*x = GetMenuResponse{}
	mi := &file_restaurant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuResponse) ProtoMessage() {}

func (x *GetMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuResponse.ProtoReflect.Descriptor instead.
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{7}
}

func (x *GetMenuResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetMenuResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemRequest) Reset() {
	*x = GetMenuItemRequest{}
	mi := &file_restaurant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemRequest) ProtoMessage() {}

func (x *GetMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{8}
}

func (x *GetMenuItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *MenuItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemResponse) Reset() {
	*x = GetMenuItemResponse{}
	mi := &file_restaurant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemResponse) ProtoMessage() {}

func (x *GetMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{9}
}

func (x *GetMenuItemResponse) GetItem() *MenuItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// GetRestaurantStatus - Check if restaurant is open and accepting orders
type GetRestaurantStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantStatusRequest) Reset() {
	*x = GetRestaurantStatusRequest{}
	mi := &file_restaurant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantStatusRequest) ProtoMessage() {}

func (x *GetRestaurantStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantStatusRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{10}
}

func (x *GetRestaurantStatusRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

type GetRestaurantStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsAcceptingOrders bool                   `protobuf:"varint,2,opt,name=is_accepting_orders,json=isAcceptingOrders,proto3" json:"is_accepting_orders,omitempty"`
	OpeningTime       string                 `protobuf:"bytes,3,opt,name=opening_time,json=openingTime,proto3" json:"opening_time,omitempty"`
	ClosingTime       string                 `protobuf:"bytes,4,opt,name=closing_time,json=closingTime,proto3" json:"closing_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRestaurantStatusResponse) Reset() {
	*x = GetRestaurantStatusResponse{}
	mi := &file_restaurant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantStatusResponse) ProtoMessage() {}

func (x *GetRestaurantStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantStatusResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{11}
}

func (x *GetRestaurantStatusResponse) GetIsAcceptingOrders() bool {
	if x != nil {
		return x.IsAcceptingOrders
	}
	return false
}

func (x *GetRestaurantStatusResponse) GetOpeningTime() string {
	if x != nil {
		return x.OpeningTime
	}
	return ""
}

func (x *GetRestaurantStatusResponse) GetClosingTime() string {
	if x != nil {
		return x.ClosingTime
	}
	return ""
}

// ValidateMenuItems - Validate multiple items are available (for order validation)
type ValidateMenuItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	ItemIds       []string               `protobuf:"bytes,2,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMenuItemsRequest) Reset() {
	*x = ValidateMenuItemsRequest{}
	mi := &file_restaurant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMenuItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMenuItemsRequest) ProtoMessage() {}

func (x *ValidateMenuItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMenuItemsRequest.ProtoReflect.Descriptor instead.
func (*ValidateMenuItemsRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateMenuItemsRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *ValidateMenuItemsRequest) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type MenuItemValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemValidation) Reset() {
	*x = MenuItemValidation{}
	mi := &file_restaurant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemValidation) ProtoMessage() {}

func (x *MenuItemValidation) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemValidation.ProtoReflect.Descriptor instead.
func (*MenuItemValidation) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{13}
}

func (x *MenuItemValidation) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *MenuItemValidation) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *MenuItemValidation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ValidateMenuItemsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllAvailable     bool                   `protobuf:"varint,1,opt,name=all_available,json=allAvailable,proto3" json:"all_available,omitempty"`
	Items            []*MenuItemValidation  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	UnavailableItems []string               `protobuf:"bytes,3,rep,name=unavailable_items,json=unavailableItems,proto3" json:"unavailable_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateMenuItemsResponse) Reset() {
	*x = ValidateMenuItemsResponse{}
	mi := &file_restaurant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMenuItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMenuItemsResponse) ProtoMessage() {}

func (x *ValidateMenuItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMenuItemsResponse.ProtoReflect.Descriptor instead.
func (*ValidateMenuItemsResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateMenuItemsResponse) GetAllAvailable() bool {
	if x != nil {
		return x.AllAvailable
	}
	return false
}

func (x *ValidateMenuItemsResponse) GetItems() []*MenuItemValidation {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ValidateMenuItemsResponse) GetUnavailableItems() []string {
	if x != nil {
		return x.UnavailableItems
	}
	return nil
}

var File_restaurant_proto protoreflect.FileDescriptor

const file_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x10restaurant.proto\x12\n" +
	"restaurant\"\xdb\x02\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x19\n" +
	"\blogo_url\x18\b \x01(\tR\alogoUrl\x12!\n" +
	"\fopening_time\x18\t \x01(\tR\vopeningTime\x12!\n" +
	"\fclosing_time\x18\n" +
	" \x01(\tR\vclosingTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xa5\x02\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\tR\frestaurantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12!\n" +
	"\fis_available\x18\a \x01(\bR\visAvailable\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"+\n" +
	"\x15GetRestaurantsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\"h\n" +
	"\x16GetRestaurantsResponse\x128\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x16.restaurant.RestaurantR\vrestaurants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"&\n" +
	"\x14GetRestaurantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x15GetRestaurantResponse\x126\n" +
	"\n" +
	"restaurant\x18\x01 \x01(\v2\x16.restaurant.RestaurantR\n" +
	"restaurant\"I\n" +
	"\x0eGetMenuRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"S\n" +
	"\x0fGetMenuResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.restaurant.MenuItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"$\n" +
	"\x12GetMenuItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x13GetMenuItemResponse\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.restaurant.MenuItemR\x04item\"A\n" +
	"\x1aGetRestaurantStatusRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\"\x93\x01\n" +
	"\x1bGetRestaurantStatusResponse\x12.\n" +
	"\x13is_accepting_orders\x18\x02 \x01(\bR\x11isAcceptingOrders\x12!\n" +
	"\fopening_time\x18\x03 \x01(\tR\vopeningTime\x12!\n" +
	"\fclosing_time\x18\x04 \x01(\tR\vclosingTime\"Z\n" +
	"\x18ValidateMenuItemsRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x19\n" +
	"\bitem_ids\x18\x02 \x03(\tR\aitemIds\"d\n" +
	"\x12MenuItemValidation\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xa3\x01\n" +
	"\x19ValidateMenuItemsResponse\x12#\n" +
	"\rall_available\x18\x01 \x01(\bR\fallAvailable\x124\n" +
	"\x05items\x18\x02 \x03(\v2\x1e.restaurant.MenuItemValidationR\x05items\x12+\n" +
	"\x11unavailable_items\x18\x03 \x03(\tR\x10unavailableItems2\xa0\x04\n" +
	"\x11RestaurantService\x12W\n" +
	"\x0eGetRestaurants\x12!.restaurant.GetRestaurantsRequest\x1a\".restaurant.GetRestaurantsResponse\x12T\n" +
	"\rGetRestaurant\x12 .restaurant.GetRestaurantRequest\x1a!.restaurant.GetRestaurantResponse\x12B\n" +
	"\aGetMenu\x12\x1a.restaurant.GetMenuRequest\x1a\x1b.restaurant.GetMenuResponse\x12N\n" +
	"\vGetMenuItem\x12\x1e.restaurant.GetMenuItemRequest\x1a\x1f.restaurant.GetMenuItemResponse\x12f\n" +
	"\x13GetRestaurantStatus\x12&.restaurant.GetRestaurantStatusRequest\x1a'.restaurant.GetRestaurantStatusResponse\x12`\n" +
	"\x11ValidateMenuItems\x12$.restaurant.ValidateMenuItemsRequest\x1a%.restaurant.ValidateMenuItemsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_restaurant_proto_rawDescOnce sync.Once
	file_restaurant_proto_rawDescData []byte
)

func file_restaurant_proto_rawDescGZIP() []byte {
	file_restaurant_proto_rawDescOnce.Do(func() {
		file_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurant_proto_rawDesc), len(file_restaurant_proto_rawDesc)))
	})
	return file_restaurant_proto_rawDescData
}

var file_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_restaurant_proto_goTypes = []any{
	(*Restaurant)(nil),                  // 0: restaurant.Restaurant
	(*MenuItem)(nil),                    // 1: restaurant.MenuItem
	(*GetRestaurantsRequest)(nil),       // 2: restaurant.GetRestaurantsRequest
	(*GetRestaurantsResponse)(nil),      // 3: restaurant.GetRestaurantsResponse
	(*GetRestaurantRequest)(nil),        // 4: restaurant.GetRestaurantRequest
	(*GetRestaurantResponse)(nil),       // 5: restaurant.GetRestaurantResponse
	(*GetMenuRequest)(nil),              // 6: restaurant.GetMenuRequest
	(*GetMenuResponse)(nil),             // 7: restaurant.GetMenuResponse
	(*GetMenuItemRequest)(nil),          // 8: restaurant.GetMenuItemRequest
	(*GetMenuItemResponse)(nil),         // 9: restaurant.GetMenuItemResponse
	(*GetRestaurantStatusRequest)(nil),  // 10: restaurant.GetRestaurantStatusRequest
	(*GetRestaurantStatusResponse)(nil), // 11: restaurant.GetRestaurantStatusResponse
	(*ValidateMenuItemsRequest)(nil),    // 12: restaurant.ValidateMenuItemsRequest
	(*MenuItemValidation)(nil),          // 13: restaurant.MenuItemValidation
	(*ValidateMenuItemsResponse)(nil),   // 14: restaurant.ValidateMenuItemsResponse
}
var file_restaurant_proto_depIdxs = []int32{
	0,  // 0: restaurant.GetRestaurantsResponse.restaurants:type_name -> restaurant.Restaurant
	0,  // 1: restaurant.GetRestaurantResponse.restaurant:type_name -> restaurant.Restaurant
	1,  // 2: restaurant.GetMenuResponse.items:type_name -> restaurant.MenuItem
	1,  // 3: restaurant.GetMenuItemResponse.item:type_name -> restaurant.MenuItem
	13, // 4: restaurant.ValidateMenuItemsResponse.items:type_name -> restaurant.MenuItemValidation
	2,  // 5: restaurant.RestaurantService.GetRestaurants:input_type -> restaurant.GetRestaurantsRequest
	4,  // 6: restaurant.RestaurantService.GetRestaurant:input_type -> restaurant.GetRestaurantRequest
	6,  // 7: restaurant.RestaurantService.GetMenu:input_type -> restaurant.GetMenuRequest
	8,  // 8: restaurant.RestaurantService.GetMenuItem:input_type -> restaurant.GetMenuItemRequest
	10, // 9: restaurant.RestaurantService.GetRestaurantStatus:input_type -> restaurant.GetRestaurantStatusRequest
	12, // 10: restaurant.RestaurantService.ValidateMenuItems:input_type -> restaurant.ValidateMenuItemsRequest
	3,  // 11: restaurant.RestaurantService.GetRestaurants:output_type -> restaurant.GetRestaurantsResponse
	5,  // 12: restaurant.RestaurantService.GetRestaurant:output_type -> restaurant.GetRestaurantResponse
	7,  // 13: restaurant.RestaurantService.GetMenu:output_type -> restaurant.GetMenuResponse
	9,  // 14: restaurant.RestaurantService.GetMenuItem:output_type -> restaurant.GetMenuItemResponse
	11, // 15: restaurant.RestaurantService.GetRestaurantStatus:output_type -> restaurant.GetRestaurantStatusResponse
	14, // 16: restaurant.RestaurantService.ValidateMenuItems:output_type -> restaurant.ValidateMenuItemsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_restaurant_proto_init() }
func file_restaurant_proto_init() {
	if File_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurant_proto_rawDesc), len(file_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurant_proto_goTypes,
		DependencyIndexes: file_restaurant_proto_depIdxs,
		MessageInfos:      file_restaurant_proto_msgTypes,
	}.Build()
	File_restaurant_proto = out.File
	file_restaurant_proto_goTypes = nil
	file_restaurant_proto_depIdxs = nil
}
